CoviDiscusion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('case/', include('case.urls')),
    path('experiences/', include('experiences.urls')),
    path('', include('login.urls'))
]

case/urls.py
from django.urls import path

from . import views

app_name = 'case'

urlpatterns = [
    path('', views.case, name='case'),
    path('detail/<int:nomor>', views.detail, name='detail'),
    path('cari/', views.cari, name='cari'),
    path('data/', views.data, name='data'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
	path('login/', views.log_in, name='log_in'),
	path('logout/', views.log_out, name='log_out'),
	path('signup/', views.signup , name='signup'),
]

case/models.py
from django.db import models

class Kasus(models.Model):
	jumlah = models.PositiveIntegerField(default = 1)
	prov = models.CharField(max_length = 50, choices= [('Aceh', 'Aceh'), ('Bali', 'Bali'), ('Banten', 'Banten'), ('Bengkulu', 'Bengkulu'), ('DIY', 'DIY'), ('DKI Jakarta', 'DKI Jakarta'), ('Gorontalo', 'Gorontalo'), ('Jambi', 'Jambi'), ('Jabar', 'Jabar'), ('Jateng', 'Jateng'), ('Jatim', 'Jatim'), ('Kalbar', 'Kalbar'), ('Kalsel', 'Kalsel'), ('Kalteng', 'Kalteng'), ('Kaltim', 'Kaltim'), ('Kaltara', 'Kaltara'), ('Babel', 'Babel'), ('Kepri', 'Kepri'), ('Lampung', 'Lampung'), ('Maluku', 'Maluku'), ('Malut', 'Malut'), ('NTB', 'NTB'), ('NTT', 'NTT'), ('Papua', 'Papua'), ('Papbar', 'Papbar'), ('Riau', 'Riau'), ('Sulbar', 'Sulbar'), ('Sulsel', 'Sulsel'), ('Sulteng', 'Sulteng'), ('Sultara', 'Sultara'), ('Sulut', 'Sulut'), ('Sumbar', 'Sumbar'), ('Sumsel', 'Sumsel'), ('Sumut', 'Sumut')])
	kotkab = models.CharField(max_length = 50)

case/forms.py
from django import forms
from .models import Kasus

class FormKasus(forms.ModelForm):
    class Meta:
        model = Kasus
        fields = "__all__"
        widgets = {
            'jumlah' : forms.NumberInput(attrs={'class': 'form-control'}),
            'prov' : forms.Select(attrs={'class': 'form-control'}),
            'kotkab' : forms.TextInput(attrs={'class': 'form-control'}),
        }

case/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import JsonResponse
from .models import Kasus
from .forms import FormKasus

def case(request):
	form = FormKasus()
	if request.method == "POST":
		form = FormKasus(request.POST)
		if form.is_valid() and request.user.is_authenticated:
			form.save()
			return redirect('case:case')
	dct = {}
	prov_list = []
	prov_all = []
	kasus = Kasus.objects.all()
	for ks in kasus:
		if ks.prov in dct :
			dct[ks.prov] += ks.jumlah
		else : 
			dct[ks.prov] = ks.jumlah
			prov_list.append(ks.prov)	
	for prov in prov_list :
		tmp = []
		for ks in kasus:
			if ks.prov in prov:
				s = ' '.join(w.capitalize() for w in ks.kotkab.split())    	
				if not s in tmp:
					tmp.append(s)
		tmp2 = []
		tmp2.append(prov)
		tmp2.append(tmp)
		tmp2.append(dct[prov])
		prov_all.append(tmp2)
		for ks in kasus:
			if ks.prov in prov:
				tmp2.append(ks)
				break
	context = {'form' : form, 'prov_all' : prov_all}
	return render(request, 'case/case.html', context)

def detail(request, nomor):
	prov = Kasus.objects.get(id = nomor)
	kasus_all = Kasus.objects.all()
	dct = {}
	data = []
	jum = 0
	for ks in kasus_all:
		if ks.prov == prov.prov:
			jum += ks.jumlah
			s = ' '.join(w.capitalize() for w in ks.kotkab.split())    	
			if s in dct:
				dct[s] += ks.jumlah
			else:
				dct[s] = ks.jumlah
	data.append(['Kota/Kabupaten', 'Jumlah'])
	for ks in dct:
		data.append([ks, dct[ks]])
	context = {'prov': prov, 'data': data, 'jum': jum}
	return render(request, 'case/detail.html', context)

def cari(request):
	return render(request, 'case/cari.html')

def data(request):
	isi = request.GET['q']
	isi = ' '.join(w.capitalize() for w in isi.split())
	kasus_all = Kasus.objects.all()
	dct = {}
	dctp = {}
	data = []
	for ks in kasus_all:
		kk = ' '.join(w.capitalize() for w in ks.kotkab.split())    	
		pp = ' '.join(w.capitalize() for w in ks.prov.split())  
		if (isi in kk) or (isi in pp):
			if kk in dct:
				dct[kk] += ks.jumlah
			else:
				dctp[kk] = ks.prov
				dct[kk] = ks.jumlah
	for ks in dct:
		data.append([dct[ks], ks, dctp[ks]])
	data.sort(reverse = True)
	return JsonResponse(data=data, safe=False)

case/templates/case/cari.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
	<title>Cari Kasus</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				<div class="text-center">
				<h1>Cari Kasus</h1>
			<br>
			</div>
			<div class="input-group mb-3 px-5">
			    <input id = "keyword" class="form-control" type="text" class="form-control" placeholder="Cari kata kunci (awal kata Provinsi atau Kota / Kabupaten)" aria-label="Recipient's username" aria-describedby="button-addon2">
			    <div class="input-group-append">
			        <button id = "cari" class="btn btn-outline-primary" type="button" id="button-addon2">Cari</button>
			    </div>
			</div>
			<table class="table">
				<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">Kota / Kabupaten</th>
					<th scope="col">Provinsi</th>
					<th scope="col">Jumlah</th>
				</tr>
				</thead>
				<tbody id="list">
				</tbody>
			</table>
			<br>
			<li>Menampilkan data terurut dari jumlah kasus terbesar</li>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
function cari() {
    var isi = $("#keyword").val();
    $.ajax({
        url : '/case/data?q=' + isi,
        success: function(data){
            var array_items = data;
            console.log(array_items);
            $("#list").empty();
            for(i = 0; i < array_items.length; i++)
            {
                $("#list").append(
                	"<tr>" +
                	"<th scope='row'>" + (i + 1) + "</th>" +
                	"<td>" + array_items[i][1] + "</td>" +
                	"<td>" + array_items[i][2] + "</td>" +
                	"<td>" + array_items[i][0] + "</td>" +
                	"</tr>"
                );
            }
        }
    })
}
$("#cari").click(cari);
$('#keyword').keyup(function(e){
    if(e.keyCode == 13) 
        cari();
});
</script>
{% endblock content %}

case/templates/case/case.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
	<title>Case</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div class="text-center">
	<h1>Yuk sampaikan update kasus di daerahmu</h1>
	<p>Sampaikan update kasus di daerahmu</p>
</div>
<div class="text-center py-3">
    {% if user.is_authenticated %}
    <a type="button" href="#sampaikan_disini" class="btn btn-light border border-secondary btn-lg font-weight-bold">SAMPAIKAN DISINI</a>
    {% else %}
    <a type="button" href="{% url 'login:log_in' %}" class="btn btn-light border border-secondary btn-lg font-weight-bold">LOG IN UNTUK SAMPAIKAN</a>
    {% endif %}
</div>
<div class="text-center">
    <a type="button" href="{% url 'case:cari' %}" class="btn btn-light border border-secondary btn-lg font-weight-bold">CARI KASUS</a>
</div>
</br>
</br>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				<h4 class="text-center pb-4">Daftar Lokasi:</h4>
				<div id="isi">
					<div class="row row-cols-3 mx-2" id="accordionExample">
						{% for prov in prov_all %}
						<div class="col-6 col-md-4 p-2">
							<div class="card border-secondary">
								<div class="card-body accordion-btn" id="judul-{{ forloop.counter }}" data-body="isi-{{ forloop.counter }}">
									<h5 class = "text-center font-weight-bold"> 
										<div class="text-body card-title text-center">{{prov.0}} : {{prov.2}}</a>
									</h5>
									<div id="isi-{{ forloop.counter }}" class="collapse" data-parent="#accordionExample">
										{% for kotkab in prov.1 %}
											<h6>
												<li> {{kotkab}} </li>
											</h6>
										{% endfor %}
									</div>
									<div class="text-right">
										<a class="text-secondary" href = "{% url 'case:detail' prov.3.id %}">Sebaran</a>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
					<br>
					<li>Arahkan kursor pada card untuk melihat detail kota / kabupaten</li>
					<li>Klik sebaran untuk melihat sebaran kasus</li>
				</div>
				<br>
				<div class="text-center">
					<button class="btn accordion-btn2" type="button" id="judul" data-body="isi">
						<h5> Tampilkan / Sembunyikan</h6>
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
</br>
</br>
{% if user.is_authenticated %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" id="sampaikan_disini" style="background: white">
				<h4 class="text-center">SAMPAIKAN DISINI</h4>
				<form class = "ml-5 mr-5 mt-2 font-weight-bold py-4" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label for="jumlah">Jumlah</label> {{form.jumlah}}
					</div>
					<div class="form-group">
						<label for="prov">Provinsi</label> {{form.prov}}
					</div>
					<div class="form-group">
						<label for="kotkab">Kota / Kabupaten</label> {{form.kotkab}}
					</div>
					<center class="pt-3">
						<a type="submit" data-toggle="modal" data-target="#exampleModal" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</a>
					</center>
					<!-- Modal -->
					<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body">
									<h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin data yang dimasukkan sudah benar?</h5>
								</div>
								<div class="modal-footer">
									<button type="submit" class="btn btn-light border border-dark font-weight-bold">Sudah</button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endif %}

<script type="text/javascript">
$(".accordion-btn").hover(function() {
    var bodyId = $(this).attr('data-body');
    $(`#${bodyId}`).slideToggle("slow");
});
$(".accordion-btn2").click(function() {
    var bodyId = $(this).attr('data-body');
    $(`#${bodyId}`).slideToggle("slow");
});
</script>
{% endblock content %}

case/templates/case/detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
	<title>{{prov.prov}}</title>
{% endblock %}

{% block content %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				<div class="text-center">
					<h1>Sebaran kasus Provinsi {{prov.prov}}</h1>
					<h2>{{jum}} Kasus</h2>
				</div>
				<div id="piechart"></div>
			</div>
		</div>	
	</div>
</div>
</br>
<div class="text-center">
	<a type="button" href="{% url 'case:case' %}" class="btn btn-light border border-dark btn-lg font-weight-bold">Kembali</a>
	
</div>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> 

<script type="text/javascript">
	// Load google charts
	google.charts.load('current', {'packages':['corechart']});
	google.charts.setOnLoadCallback(drawChart);

	// Draw the chart and set the chart values
	function drawChart() {
	  var data = google.visualization.arrayToDataTable({{data|safe}});

	  // Optional; add a title and set the width and height of the charts
	  var options = {
	    'pieSliceText': 'value-and-percentage',
        'labels': 'none',
        'height': '500',
      };

	  // Display the chart inside the <div> element with id="piechart"
	  var chart = new google.visualization.PieChart(document.getElementById('piechart'));
	  chart.draw(data, options);
	}
</script>

{% endblock content %}