CoviDiscusion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('case/', include('case.urls')),
    path('experiences/', include('experiences.urls')),
    path('', include('login.urls'))
]

case/urls.py
from django.urls import path

from . import views

app_name = 'case'

urlpatterns = [
    path('', views.case, name='case'),
    path('detail/<int:nomor>', views.detail, name='detail'),
    path('cari/', views.cari, name='cari'),
    path('data/', views.data, name='data'),
]

experiences/urls.py
from django.urls import path

from .views import experiences, saveexperience, deleteexperience, cariexperiences, dataexperiences

app_name = 'experiences'

urlpatterns = [
    path('', experiences, name='experiences'),
    path('saveexperience', saveexperience, name='saveexperience' ),
    path('deleteexperience/<str:pk>', deleteexperience, name='deleteexperience'),
    path('cari', cariexperiences, name='cari'),
    path('data', dataexperiences, name='data'),

]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
	path('login/', views.log_in, name='log_in'),
	path('logout/', views.log_out, name='log_out'),
	path('signup/', views.signup , name='signup'),
]

experiences/models.py
from django.db import models
from login.models import Profile

# Create your models here.
class Experience(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    pengalaman = models.TextField()

experiences/forms.py
from django import forms
from .models import Experience

class FormExperience(forms.ModelForm):
    class Meta:
        model = Experience
        fields = "__all__"
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'lokasi' : forms.TextInput(attrs={'class': 'form-control'}),
            'pengalaman' : forms.Textarea(attrs={'class': 'form-control'}),
        }

experiences/views.py
from django.shortcuts import render, redirect
from .forms import FormExperience
from .models import Experience
from login.models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core import serializers

# Create your views here.
def experiences(request):
    return render(request, 'experiences/experiences.html', {'experiences' : Experience.objects.all()})
    
@login_required(login_url='login:login')
def cariexperiences(request):
    return render(request, 'experiences/cariexperiences.html')

@login_required(login_url='login:login')
def dataexperiences(request):
    param = request.GET['q']
    param = param.capitalize()
    hasil = []
    key = 0
    experience_all = Experience.objects.all()

    for experience in experience_all:
        username = experience.profile.user.username
        kab_kota = experience.profile.kota_kabupaten
        provinsi = experience.profile.provinsi
        pengalaman = experience.pengalaman

        dataex = {'username':username, 'kota_kabupaten':kab_kota, 'provinsi':provinsi, 'pengalaman':pengalaman, }

        if (param in username.capitalize()) or (param in kab_kota.capitalize()) or (param in provinsi.capitalize()) or (param in pengalaman.capitalize()):
            hasil.append(dataex)
            key += 1

    return JsonResponse(hasil, safe=False)

@login_required(login_url='login:login')
def saveexperience(request): 
    experience = request.POST['pengalaman']
    if request.user.is_authenticated and request.method == 'POST':
        profile = request.user.profile
        new = Experience(profile=profile, pengalaman=experience)
        new.save()
        experience = {'id': new.id , 'username': new.profile.user.username, 'provinsi' : new.profile.provinsi, 'kota_kabupaten' : new.profile.kota_kabupaten, 'pengalaman' : new.pengalaman, }
        data = {
            "experience" : experience,
        }

        return JsonResponse(data)    
    


@login_required(login_url='login:login')
def deleteexperience(request, pk):
    experience = Experience.objects.get(id=pk)
    if request.method == 'POST':
        experience.delete()

    return redirect('experiences:experiences')

experiences/templates/experiences/cariexperiences.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Share Experiences</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}

<div class="container-fluid my-5 mx-auto text-center" style="max-width: 810px;">
    <h1>Cari pengalaman yang dinginkan</h1>
    <h6 class="mt-4 mx-2 text-muted">Tuliskan username, lokasi, maupun pengalaman yang ingin dicari. Tekan tombol di bawah untuk memunculkan kolom pencarian</h6>
    <a type="button" id="start" href="" class="my-3 btn btn-light border border-secondary btn-lg font-weight-bold">Mulai Cari Pengalaman</a>
</div>


<div id="result" class="container-fluid">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-dark p-3" style="background: white">
				
                <div class="input-group input-group-lg mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-lg">Cari Pengalaman</span>
                    </div>
                    <input type="text" id="pencarian" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">
                    <div class="input-group-append">
                        <button id="cari" class="btn btn-outline-primary" type="button" id="button-addon2">Cari</button>
                    </div>
                </div>
                
                <div id="list">

                </div>
		</div>
	</div>
</div>

<script>
$(document).ready(function () {
    function cari() {
        var param = $("#pencarian").val();

        $.ajax({
            url: '/experiences/data?q=' + param,
            success: function (response) {
                
                for (i = 0 ; i < response.length; i++) {
                    $("#list").append(
                        '<div class="card border-white"><div class="card-body"><h4 class="card-title">' + response[i].username + 
                        '</h4><p class="card-subtitle mb-3 text-muted">' +  response[i].kota_kabupaten + ',' +  response[i].provinsi + 
                        '</p><h5 class="card-text">' +  response[i].pengalaman + '</h5></div><hr class="mx-5 my-1"></div>'
                    );
                    
                }
            }
        });
    }

    $('#cari').click(function(e){
        $("#list").empty();
        cari();
    });


    $("#result").hide();


    $("#start").click(function (e) { 
        e.preventDefault();
        $("#result").slideDown();
    });    
});

</script>


{% endblock content %}

experiences/templates/experiences/experiences.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Share Experiences</title>
    <script type="text/javascript" src="{% static 'js/experiences.js' %}"></script>
{% endblock %}

{% block content %}

<div class="container-fluid my-5 mx-auto text-center" style="max-width: 810px;">
    <h1>Yuk sampaikan pengalamanmu selama masa pandemi</h1>
    <h6 class="mt-4 mx-2 text-muted">Sampaikan pengalaman selama PJJ, WFH, SFH, atau pengalaman lainnya selama masa pandemi</h6>
</div>

<div class="text-center py-3">
    {% if user.is_authenticated %}
    <a type="button" href="#sampaikan_disini" class="btn btn-light border border-secondary btn-lg font-weight-bold">SAMPAIKAN DISINI</a>
    <div class="text-center py-3">
        <a type="button" href="{% url 'experiences:cari' %}" class="btn btn-light border border-secondary btn-lg font-weight-bold">CARI PENGALAMAN</a>
    </div>
    {% else %}
    <a type="button" href="{% url 'login:log_in' %}" class="btn btn-light border border-secondary btn-lg font-weight-bold">LOG IN UNTUK CARI & SAMPAIKAN</a>
    {% endif %}
</div>

<div class="container-fluid my-5">
	<div class="row overflow-auto">
		<div class="col-md-8 offset-md-2 ">
            <div class="rounded-lg border border-secondary p-3"  style="background: white">
                {% if experiences %}
                <div class="container-fluid  overflow-auto" id="daftar" style="max-height: 450px;">
                    {% for pengalaman in experiences %}
                    <div class="card border-white">
                        <div class="card-body">
                          <h4 class="card-title">{{ pengalaman.profile.user.username}}</h4>
                          <p class="card-subtitle mb-3 text-muted">{{ pengalaman.profile.kota_kabupaten }}, {{ pengalaman.profile.provinsi }}</p>
                          <h5 class="card-text">{{ pengalaman.pengalaman }}</h5>
                         
                          {% if user.is_authenticated and user == pengalaman.profile.user %}
                          <button type="reset" class="btn float-right" data-toggle="modal" data-target="#exampleModal{{ pengalaman.id }}">
                            <img src="{% static 'img/trash.png' %}" width="20" height="20" alt="trash">
                          </button>
                          {% endif %}
                        </div>
                        <hr class="mx-5 my-1">
                    </div>

                    
                    <div class="modal fade" id="exampleModal{{ pengalaman.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Peringatan</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                                <h4>Apakah anda ingin menghapus tanggapan ini?</h4>

                                <div class="card border-white">
                                    <div class="card-body">
                                      <h4 class="card-title">{{ pengalaman.profile.user.username}}</h5>
                                      <p class="card-subtitle mb-3 text-muted">{{ pengalaman.profile.kota_kabupaten }}, {{ pengalaman.profile.provinsi }}</p>
                                      <h5 class="card-text">{{ pengalaman.pengalaman }}</h5>
                                    </div>
                                </div>
                               
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                            <form class="text-center" action="{% url 'experiences:deleteexperience' pengalaman.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Hapus</button>
                            </form>

                            </div>
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
			</div>
		</div>
    </div>
</div>

{% if user.is_authenticated %}
<div class="container-fluid my-5" id="sampaikan_disini">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="rounded-lg border border-secondary p-3" style="background: white">
				<h4 class="text-center">SAMPAIKAN DISINI</h4>
				<form class = "ml-5 mr-5 mt-2 font-weight-bold py-4" id="saveexperience" method="POST">
                    {% csrf_token %}
					<div class="form-group">
                        <label for="pengalaman">Pengalaman kamu</label>
                        <textarea class="form-control" name="pengalaman" id="pengalaman" rows="10"></textarea>
					</div>
					<center class="pt-3">
                        <button type="submit" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</button>
                    </center>
				</form>
			</div>
		</div>
    </div>
</div>
{% endif %}

{% endblock content %}