CoviDiscusion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('case/', include('case.urls')),
    path('experiences/', include('experiences.urls')),
    path('', include('login.urls'))
]

case/urls.py
from django.urls import path

from . import views

app_name = 'case'

urlpatterns = [
    path('', views.case, name='case'),
    path('detail/<int:nomor>', views.detail, name='detail'),
    path('cari/', views.cari, name='cari'),
    path('data/', views.data, name='data'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
	path('login/', views.log_in, name='log_in'),
	path('logout/', views.log_out, name='log_out'),
	path('signup/', views.signup , name='signup'),
]

main/urls.py
from django.urls import path

from . import views
from .views import savesaran, deletesaran

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savesaran', savesaran, name='savesaran'),
    path('deletesaran/<str:pk>', deletesaran, name='deletesaran'),
    path('like/', views.like, name='like'),
    path('cari/', views.cari, name='cari'),
    path('data/', views.data, name='data'),
]

main/models.py
from django.db import models

class Saran(models.Model):
	nama = models.CharField(max_length=50, null=True, blank=True)
	lokasi = models.CharField(max_length=50, null=True, blank=True)
	saran = models.TextField()

class Like(models.Model):
    saran_lk = models.ForeignKey(Saran, on_delete=models.CASCADE)

main/forms.py
from django import forms
from .models import Saran

class FormSaran(forms.ModelForm):
    class Meta:
        model = Saran
        fields = "__all__"
        widgets = {
            'nama' : forms.TextInput(attrs={'class': 'form-control'}),
            'lokasi' : forms.TextInput(attrs={'class': 'form-control'}),
            'saran' : forms.Textarea(attrs={'class': 'form-control'}),
        }

main/views.py
from django.shortcuts import render, redirect
from .models import Saran, Like
from django.http import HttpResponse
from .forms import FormSaran
from django.template.loader import render_to_string
from django.http import JsonResponse

def home(request):
    return render(request, 'main/home.html', {'form':FormSaran, 'saran':Saran.objects.all()})

def savesaran(request):
	saran = FormSaran(request.POST or None)
	if saran.is_valid() and request.method == 'POST':
		if request.user.is_authenticated:
			saran.save()
	return redirect('main:home')

def deletesaran(request, pk):
	saran = Saran.objects.get(id=pk)
	if request.method == 'POST':
		saran.delete()
	return redirect('main:home')

def like(request):
	if request.method == 'GET':
		saran_id = request.GET['saran_id']
		likedsaran = Saran.objects.get(pk=saran_id) #getting the liked posts
		m = Like(saran_lk=likedsaran) # Creating Like Object
		m.save()  # saving it to store in database
		return HttpResponse("Success!") # Sending an success response

def cari(request):
	return render(request, 'main/cari.html')

def data(request):
	isi = request.GET['q']
	saran_all = Saran.objects.all()
	data = []
	for sr in saran_all:
		nm = sr.nama
		loc = sr.lokasi
		if (isi.lower() in nm.lower()) or (isi.lower() in loc.lower()):
			data.append([nm, loc, sr.saran])
	return JsonResponse(data=data, safe=False)

main/templates/main/cari.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Cari Saran</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %} {% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <div class="text-center">
                    <h1>Cari Saran</h1>
                    <br>
                </div>
                <div class="input-group mb-3 px-5">
                    <input id="keyword" class="form-control" type="text" class="form-control" placeholder="Cari kata kunci berdasarkan nama/lokasi" aria-label="Recipient's username" aria-describedby="button-addon2">
                    <div class="input-group-append">
                        <button id="cari" class="btn btn-outline-primary" type="button" id="button-addon2">Cari</button>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Lokasi</th>
                            <th scope="col">Saran</th>
                        </tr>
                    </thead>
                    <tbody id="list">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function cari() {
        var isi = $("#keyword").val();
        $.ajax({
            url: '/data?q=' + isi,
            success: function(data) {
                var array_items = data;
                console.log(array_items);
                $("#list").empty();
                for (i = 0; i < array_items.length; i++) {
                    $("#list").append(
                        "<tr>" +
                        "<th scope='row'>" + (i + 1) + "</th>" +
                        "<td>" + array_items[i][0] + "</td>" +
                        "<td>" + array_items[i][1] + "</td>" +
                        "<td>" + array_items[i][2] + "</td>" +
                        "</tr>"
                    );
                }
            }
        })
    }
    $("#cari").click(cari);
    $('#keyword').keyup(function(e) {
        if (e.keyCode == 13)
            cari();
    });
</script>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>CoviDiscussion</title>
{% endblock meta %} {% block content %}
<div class="text-center">
    <h1>Selamat Datang di CoviDiscussion</h1>
    <p>Tempat untuk saling diskusi dan bercerita tentang COVID-19</p>
</div>

<div class="container-fluid">
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">APA ITU COVID -19</h4>
                <p class="text-center pl-3 pr-3">Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem
                    pernapasan, infeksi paru-paru yang berat, hingga kematian.</p>
            </div>
        </div>
    </div>
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">PEYEBARAN COVID-19</h4>
                <p class="text-center pl-3 pr-3">Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem
                    pernapasan, infeksi paru-paru yang berat, hingga kematian.</p>
            </div>
        </div>
    </div>
    <div class="row my-5">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-dark p-3" style="background: white">
                <h4 class="text-center pb-4">CARA PENCEGAHAN COVID-19</h4>
                <p class="pl-3 pr-3">Cara pencegahan Covid-19 :
                    <ol>
                        <li>Cuci tangan Anda secara rutin. Gunakan sabun dan air, atau cairan pembersih tangan berbahan alkohol.</li>
                        <li>Selalu jaga jarak aman dengan orang yang batuk atau bersin.</li>
                        <li>Kenakan masker jika pembatasan fisik tidak dimungkinkan.</li>
                        <li>Jangan sentuh mata, hidung, atau mulut Anda.</li>
                        <li>Saat batuk atau bersin, tutup mulut dan hidung Anda dengan lengan atau tisu.</li>
                        <li>Jangan keluar rumah jika merasa tidak enak badan.</li>
                        <li>Jika demam, batuk, atau kesulitan bernapas, segera cari bantuan medis.</li>
                    </ol>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid my-5">
    <div class="row overflow-auto">
        <div class="col-md-8 offset-md-2 ">
            <div class="rounded-lg border border-secondary p-3" style="background: white">
                {% if saran %}
                <div class="container-fluid  overflow-auto" style="height: 450px;" id="daftarsaran">
                    {% for saran in saran %}
                    <div class="card border-white">
                        <div class="card-body">
                            <div style="display: inline-flex;">
                                <h4 class="card-title mr-4">{{ saran.nama}}</h4>
                                <p class="card-subtitle mt-1 text-muted">{{ saran.lokasi }}</p>
                            </div>
                            <h5 class="card-text">{{ saran.saran }}</h5>
                            {% if user.is_authenticated %}
                            <a class="likebutton btn btn-primary" id="like{{ saran.id }}" href="#daftarsaran" data-catid="{{ saran.id }}">Like</a>
                            <button type="reset" class="btn float-right" data-toggle="modal" data-target="#exampleModal{{ saran.id }}">
                            <img src="{% static 'img/trash.png' %}" width="20" height="20" alt="trash">
                          </button> {% endif %}
                        </div>
                        <hr class="mx-5">
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{ saran.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Peringatan</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                                </div>
                                <div class="modal-body">
                                    <h4>Apakah anda ingin menghapus tanggapan ini?</h4>

                                    <div class="card border-white">
                                        <div class="card-body">
                                            <h4 class="card-title">{{ saran.nama}}</h5>
                                                <p class="card-subtitle mb-3 text-muted">{{ saran.lokasi }}</p>
                                                <h5 class="card-text">{{ saran.saran }}</h5>
                                        </div>
                                    </div>

                                </div>

                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <form class="text-center" action="{% url 'main:deletesaran' saran.id %}" method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Hapus</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="text-center">
                    <a type="button" href="{% url 'main:cari' %}" class="btn btn-light border border-secondary btn-lg font-weight-bold">Cari Saran</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid my-5" id="saran">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="rounded-lg border border-secondary p-3" style="background: white">
                <h4 class="text-center">SARAN</h4>
                {% if user.is_authenticated %}
                <form class="ml-5 mr-5 mt-2 font-weight-bold py-4" action="{% url 'main:savesaran' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="nama">Nama</label> {{form.nama}}
                    </div>
                    <div class="form-group">
                        <label for="lokasi">Lokasi</label> {{form.lokasi}}
                    </div>
                    <div class="form-group">
                        <label for="saran">Saran kamu</label> {{form.saran}}
                    </div>
                    <center class="pt-3">
                        <a type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-light border border-dark font-weight-bold">SAMPAIKAN</a>
                    </center>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h6 class="modal-title" id="exampleModalLabel">Peringatan</h6>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
                                </div>
                                <div class="modal-body">
                                    <h5 class="modal-title" id="exampleModalLabel">Apakah anda yakin data yang dimasukkan sudah benar?</h5>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-light border border-dark font-weight-bold">Sudah</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                {% else %}
                <div class="text-center py-3">
                    <a type="button" href="{% url 'login:log_in' %}" class="btn btn-light border border-secondary font-weight-bold">LOG IN UNTUK MENYAMPAIKAN SARAN</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script type="text/javascript">
    $('.likebutton').click(function() {
        var id;
        id = $(this).attr("data-catid");
        $.ajax({
            type: "GET",
            url: "/like",
            data: {
                saran_id: id
            },
            success: function(data) {
                $('#like' + id).removeClass('btn btn-primary');
                $('#like' + id).addClass('btn btn-success');
            }
        })
    });
</script>
{% endblock content %}